config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#index"
  resources :restaurants,  only: [:new, :create, :show, :index] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def index
    @restaurants = Restaurant.all
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.'
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light" style="background-color: purple;">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="/" class="navbar-brand" style="color: white";>Restro-Review</a>
        </div>
        <div>
          <ul class="nav navbar-nav navbar-right p-2">
            <li><a href="/restaurants/new" class="btn btn-outline-light">New Restaurant</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_list.html.erb
<div>
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<div>
  <h1 class="mb-3"><strong>
    <%= restaurant.name %>
  </h1></strong>
  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Cuisine:</strong>
    <%= restaurant.category.capitalize %>
  </p>

</div>

app/views/restaurants/index.html.erb
<h1 class="mt-3"><strong>Restaurants:</strong></h1>
<div class="row mt-3">
  <% @restaurants.each do |restaurant| %>
    <div class="card col-3">
      <div class="card-body">
        <h5 class="card-title"><%= restaurant.name %></h5>
        <p class="card-text"><%= restaurant.category %> cuisine</p>
        <%= link_to "See more", restaurant_path(restaurant.id), class: "purple btn btn-sm mb-1" %>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/restaurants/new.html.erb
<h1 class="mt-3">New Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit "Submit", class: "btn btn-outline-success" %>
<% end %>

app/views/restaurants/show.html.erb
<br>
<%= render @restaurant %>

<div class="row">
  <div class="col-6">
    <p><strong>Reviews</strong></p>
    <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <p>
          <% review.rating.times do %>
            <%= "⭐" %>
          <% end %>
        </p>
        <p><%= "-" + review.content %></p>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="col-6">
    <h5><strong>Add new review:</strong></h5>
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "purple btn" %>
    <% end %>
  </div>
</div>
<%# <p> %>
  <%# link_to "Add a review", new_restaurant_review_path(params[:id]), class: "btn btn-sm btn-outline-secondary" %>
<%# </p> %>